@extends('cd.base')
@section('content')
    @include('dg.partials.resource-table', [
        'title' => 'Performances',
        'items' => $les_performances,
        'columns' => [
            ['key' => 'employe.nom', 'label' => 'Employé'],
            ['key' => 'evaluateur.name', 'label' => 'Évaluateur'],
            ['key' => 'periode_debut', 'label' => 'Début', 'type' => 'date'],
            ['key' => 'periode_fin', 'label' => 'Fin', 'type' => 'date'],
            ['key' => 'cote_generale', 'label' => 'Cote générale /60'],
            ['key' => 'statut', 'label' => 'Statut', 'type' => 'status'],
        ],
        'resource' => 'performances',
        'fields' => [
            [
                'key' => 'employe_id',
                'label' => 'Employé',
                'type' => 'select',
                'options' => 'employes',
                'required' => true,
            ],
            [
                'key' => 'evaluateur_id',
                'label' => 'Évaluateur',
                'type' => 'select',
                'options' => 'users',
            ],
            ['key' => 'periode_debut', 'label' => 'Période début', 'type' => 'date', 'required' => true],
            ['key' => 'periode_fin', 'label' => 'Période fin', 'type' => 'date', 'required' => true],
            ['key' => 'objectifs', 'label' => 'Objectifs', 'type' => 'textarea'],
            [
                'key' => 'qualite_travail',
                'label' => 'Qualité du travail /10',
                'type' => 'number',
                'step' => '0.1',
                'min' => '0',
                'max' => '10',
            ],
            [
                'key' => 'productivite',
                'label' => 'Productivité /10',
                'type' => 'number',
                'step' => '0.1',
                'min' => '0',
                'max' => '10',
            ],
            [
                'key' => 'ponctualite',
                'label' => 'Ponctualité /10',
                'type' => 'number',
                'step' => '0.1',
                'min' => '0',
                'max' => '10',
            ],
            [
                'key' => 'assiduite',
                'label' => 'Assiduité /10',
                'type' => 'number',
                'step' => '0.1',
                'min' => '0',
                'max' => '10',
            ],
            [
                'key' => 'comportement',
                'label' => 'Comportement /10',
                'type' => 'number',
                'step' => '0.1',
                'min' => '0',
                'max' => '10',
            ],
            [
                'key' => 'travail_equipe',
                'label' => 'Travail d’équipe /10',
                'type' => 'number',
                'step' => '0.1',
                'min' => '0',
                'max' => '10',
            ],
            [
                'key' => 'appreciation',
                'label' => 'Appréciation',
                'type' => 'select',
                'options' => collect([
                    ['value' => 'Mediocre', 'label' => 'Mediocre'],
                    ['value' => 'Assez Bien', 'label' => 'Assez Bien'],
                    ['value' => 'Bien', 'label' => 'Bien'],
                    ['value' => 'Très bien', 'label' => 'Très bien'],
                    ['value' => 'Excellent', 'label' => 'Excellent'],
                ]),
            ],
            ['key' => 'recommandations', 'label' => 'Recommandations', 'type' => 'textarea'],
            [
                'key' => 'statut',
                'label' => 'Statut',
                'type' => 'select',
                'options' => collect([
                    ['value' => 'brouillon', 'label' => 'Brouillon'],
                    ['value' => 'soumise', 'label' => 'Soumise'],
                    ['value' => 'validee', 'label' => 'Validée'],
                ]),
            ],
            [
                'key' => 'annee_id',
                'label' => 'Année',
                'type' => 'select',
                'options' => 'annees',
                'required' => true,
            ],
        ],
    ])
@endsection
